In [3]:
import torch
a=torch.tensor([[1,2,3,4,5]])
print(a)
print(a.shape)
print(a.size())

tensor([[1, 2, 3, 4, 5]])
torch.Size([1, 5])
torch.Size([1, 5])


In [37]:
import torch
a=torch.tensor([[1,2,3],[6,7,8]])
b=torch.tensor([1,1,3])
print(a[1,1])
print(a[1:3])
print(b[0])


tensor(7)
tensor([[6, 7, 8]])
tensor(1)


In [23]:
        #concetanation
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[1,3,4]])
c=torch.cat((a,b),dim=0)
d=torch.cat((a,b),dim=1)
print(c)
print(d)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 3, 4]])
tensor([[1, 2, 3, 7, 8, 9],
        [4, 5, 6, 1, 3, 4]])


In [24]:
import torch
a=torch.tensor([[8,9,13],[3,15,28],[1,2,3],[1,2,3]])
b=torch.tensor([[3,15,1],[8,9,1],[1,2,1]])
c=torch.cat((a,b),dim=0)
print(c)

tensor([[ 8,  9, 13],
        [ 3, 15, 28],
        [ 1,  2,  3],
        [ 1,  2,  3],
        [ 3, 15,  1],
        [ 8,  9,  1],
        [ 1,  2,  1]])


In [27]:
import torch
a=torch.tensor([[1,9],[1,8]])
b=torch.tensor([[1,2],[1,2]])
c=torch.cat((a,b),dim=1)
print(c)
#rows or columns must be equal

tensor([[1, 9, 1, 2],
        [1, 8, 1, 2]])


In [31]:
#splitting
import torch
a=torch.tensor([1,2,3,4,5,6])
c=torch.split(a,3)
print(c)
"""a=torch.arange(1,21)
d=torch.split(a,13)
print(d)"""
#a=torch.arange(1,21)
#e=torch.tensor(a,[5,3,2,5,5])
#print(e)
d=torch.chunk(a,3)
print(d)

(tensor([1, 2, 3]), tensor([4, 5, 6]))
(tensor([1, 2]), tensor([3, 4]), tensor([5, 6]))


In [7]:
import torch
a=torch.tensor([1,2,3])
print(a.size())

torch.Size([3])


In [24]:
#operations
import torch
a=torch.tensor([[5,6,7],[8,9,10]],dtype=float)
print(a.sum())
print(a.sum(dim=0))
print(a.sum(dim=1))
print(a.mean(dim=0))
print(a.mean(dim=1))

tensor(45., dtype=torch.float64)
tensor([13., 15., 17.], dtype=torch.float64)
tensor([18., 27.], dtype=torch.float64)
tensor([6.5000, 7.5000, 8.5000], dtype=torch.float64)
tensor([6., 9.], dtype=torch.float64)


In [31]:
import torch
a=torch.tensor([[5,6,7],[8,9,10]])
print(a.max())
print(a.max(dim=0))
print(a.max(dim=1))


tensor(10)
torch.return_types.max(
values=tensor([ 8,  9, 10]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([ 7, 10]),
indices=tensor([2, 2]))


In [2]:
import torch
a=torch.tensor([[5,6,7]])
print(a.size())
#[2,3,4,5]=1D tensor
#(2,4,5)=dimensions

torch.Size([1, 3])


In [35]:
import torch
a=torch.tensor([5,6,7])
print(a.argmax()) #it give sindex of the maximum number
print(a.argmin())

tensor(2)
tensor(0)


In [32]:
import torch
a=torch.tensor([[10,4,3],[8,3,2]])
b=torch.tensor([[3,5],[4,8],[1,2]])
print(a.matmul(b))
print(torch.matmul(a,b))

tensor([[49, 88],
        [38, 68]])
tensor([[49, 88],
        [38, 68]])


In [50]:
import torch
a=torch.tensor([[10,4,3],[8,3,2]])
b=torch.tensor([[3,5],[4,8],[1,2]])
print(a@b)

tensor([[49, 88],
        [38, 68]])


In [52]:
import torch
a=torch.tensor(["Siri"])
a
#tensor can't allow strings

ValueError: too many dimensions 'str'

In [53]:
#library-predefined code
#ex-numpy,pandas,matplotlib

#framework-path for developing application,software,syatem
#ex-tensor flow,pytorch

#tensorflow -ML,DL framework--->developed by google
#Tensor +flow
#tensor--element storing in multiple directions
#flow-performing operations with tensors

#USES of tensorflow
#-->building nueral network
#-->model training and saving



In [54]:
#CUDA-compute unified Demice Architecture

In [4]:
import torch
a=torch.tensor([[10,4,3],[8,3,2]])
a.device
#torch.cuda.is_available()
#CuDa.to_is_available()

device(type='cpu')

                                            attributes

In [8]:
import torch
a=torch.tensor([[1,2,3],[4,5,6],[8,9,10]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.device)


torch.Size([3, 3])
2
torch.int64
cpu


                                                Function

In [18]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.size())
print(a.numel())
print(a.sum())
print(a.float().mean())
print(a.max())
print(a.min())
print(a.sqrt())
print(a.abs())
print(a.float())
print(a.reshape(3,2))

torch.Size([2, 3])
6
tensor(21)
tensor(3.5000)
tensor(6)
tensor(1)
tensor([[1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2],
        [3, 4],
        [5, 6]])
